# Generated by Django 5.0.2 on 2024-03-01 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_category_subscriber'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='subscriber',
            new_name='subscribers',
        ),
    ]
